---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://jenkins.grink.us/job/kartais.lt/build?token=13A73DD7CF9554A2491E7D88D2237586E8EE8A39F6D644791A87EA2DB2C1CB31E32B4BBE3A6AB639CFB6DB7
sections:
- type: directory
  path: posts
  label: Blog posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
